window.Config = {
  VIEWBOX: "-200 0 2600 3300",
  NODE_RADIUS: 35,
  TEXTBOX_PADDING: 12,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 50,
  LABELS_SEPARATION: 25,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
