window.Config = {
  VIEWBOX: "-50 0 2000 2300",
  NODE_RADIUS: 26,
  TEXTBOX_PADDING: 7,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 40,
  LABELS_SEPARATION: 8,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
