window.Config = {
  VIEWBOX: "-200 00 2000 2000",
  NODE_RADIUS: 26,
  TEXTBOX_PADDING: 6,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 40,
  LABELS_SEPARATION: 5,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
