window.Config = {
  VIEWBOX: "0 0 1600 1300",
  NODE_RADIUS: 20,
  TEXTBOX_PADDING: 5,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 20,
  LABELS_SEPARATION: 10,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
