window.Config = {
  VIEWBOX: "-200 0 3500 3000",
  NODE_RADIUS: 26,
  TEXTBOX_PADDING: 8,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 40,
  LABELS_SEPARATION: 14,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
