window.Config = {
  VIEWBOX: "0 0 2000 2000",
  NODE_RADIUS: 23,
  TEXTBOX_PADDING: 8,
  LABELS_ORIGIN_X: 30,
  LABELS_ORIGIN_Y: 5,
  LABELS_HEIGHT: 35,
  LABELS_SEPARATION: 14,
  LINK_STRENGTH: 0,
  DATA_SOURCE: "English-T.csv",
  USE_EDITOR: false
}
